version = 1

[[analyzers]]
name = "javascript"
enabled = true

    [analyzers.meta]
    dependency_file_paths = [
        "backend/"
    ]
    environment = [
        "nodejs",
        "jest"
    ]
    module_system = "commonjs"