name: Backend Pipeline - CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v3
      
      - name: Use NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install ./backend

      - name: Run tests
        run: npm run --prefix ./backend test

      - name: Docker login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          file: ./backend/Dockerfile
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_REPOSITORY }}:latest
            ${{ secrets.DOCKER_REGISTRY_REPOSITORY }}:${{ github.run_number }}
  
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v3
        
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.7
        with:
          images: ${{ secrets.DOCKER_REGISTRY_REPOSITORY }}:${{ github.run_number }}
          manifests: ./infra/k8s/backend.yml
